"""Initial migration.

Revision ID: b9aa446757a9
Revises: 
Create Date: 2022-04-16 19:59:35.684782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aa446757a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('auto_id', sa.Integer(), nullable=False),
    sa.Column('name_auto', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rent_price', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.Column('img_url2', sa.String(length=128), nullable=True),
    sa.Column('img_url3', sa.String(length=128), nullable=True),
    sa.Column('img_url4', sa.String(length=128), nullable=True),
    sa.Column('rent_status', sa.String(length=128), nullable=True),
    sa.Column('car_availability', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_table('rent_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id2', sa.Integer(), nullable=True),
    sa.Column('beginning_date', sa.String(length=128), nullable=True),
    sa.Column('end_date', sa.String(length=128), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bookings_number', sa.Integer(), nullable=True),
    sa.Column('total_minute', sa.String(length=128), nullable=True),
    sa.Column('total_second', sa.String(length=128), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_journal')
    op.drop_table('rent_history')
    op.drop_table('auto')
    # ### end Alembic commands ###
